os: linux

language: ruby

addons:
  sbom:
    input: "."
    output: "sbom"
    format: "cyclonedx-json"

before_install:
  - gem install bundler

script:
  - bundle install
  - bundle exec rake test

after_success:
  - echo "Build successful"
  - ls -l sbom

after_failure:
  - echo "Build failed"
  - ls -l sbom
