os: linux

language: java
services:
  - docker
cache: bundler
dist: focal

install: skip

jobs:
  include:
    - name: "SBOM generation example job"
      addons:
        sbom:
          on:
            branch: main

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT
after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
