os: linux

language: ruby

cache:
  directories:
    - vendor/bundle

addons:
  sbom:
    input: "."
    output: "sbom"
    format: "cyclonedx-json"

before_install:
  - gem install bundler

script:
  - bundle install
  - echo "Running simple test..."
  - ruby -e "puts 'Hello, world!'"

after_success:
  - echo "Build successful"
  - ls -l sbom

after_failure:
  - echo "Build failed"
  - ls -l sbom
