language: ruby
rvm:
  - 2.7.2

addons:
  sbom:
    run_phase: 'after_success'
    output_format: 'cyclonedx-json'
    input_dir: '.'
    output_dir: 'sbom'

script:
  - echo "Testing SBOM generation"

after_success:
  - ls -la sbom
