os: linux

language: ruby

dist: focal

install: skip

jobs:
  include:
    - name: failing
      script: true

jobs:
  include:
    - os: linux
      dist: focal
      addons:
        sbom:                                          # new node
          on:
            branch: main                 # branch of the repository
          run_phase: after_success                   # when SBOM generation should be executed; see below
          output_format: cyclonedx-json              # SBOM file(s) output format
          input_dir: .                     # relative paths within build job environments, see below
          output_dir: /sbom


after_success:
  - echo "Build successful"
  - ls -l sbom

after_failure:
  - echo "Build failed"
  - ls -l sbom
